apiVersion: v1
kind: Pod
metadata:
  name: bpf-pod
  namespace: default
  labels:
    app: inject-bpf
    environment: production
spec:
  containers:
  - name: centos
    image: centos
    command: 
      - "sh"
      - "-c"
      - |
        cd /etc/yum.repos.d/ &&
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* &&
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* &&
        dnf install -y gcc &&
        dnf install -y elfutils-libelf-devel libcap-devel zlib-devel binutils-devel bpftool &&
        sleep 999
    securityContext:
      privileged: true
