apiVersion: v1
kind: Pod
metadata:
  name: dodgy-pod
  namespace: default
spec:
  containers:
  - name: centos
    image: centos
    command: ['sh', '-c', 'sleep 999']
    securityContext:
       privileged: true
