apiVersion: v1
kind: Pod
metadata:
  name: root-user-pod
spec:
  containers:
  - name: root-container
    image: ubuntu
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 0  # This specifies that the container runs as root
